# for development

services:
  frontend:
    build: ./frontend
    volumes:
      - ./frontend:/app
    ports:
      - 8080:80
    command: npm run dev -- --host --port 80 --clearScreen false

  backend:
    build: ./backend
    volumes:
      - ./backend:/app
    ports:
      - 8081:80
    environment:
      LOG_LEVEL: DEBUG
      CORS_ALLOW_ORIGIN: http://localhost:8080
    command: adev runserver --port 80 .
